# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.12"
    config.vm.hostname = "backend.dev"
    config.vm.synced_folder ".", "/var/www", :nfs => true

    config.vm.provision "shell", inline: <<-SHELL
        sudo mkdir /var/www/dist
        sudo sed -i s,/var/www/public,/var/www/dist,g /etc/apache2/sites-available/000-default.conf
        sudo sed -i s,/var/www/public,/var/www/dist,g /etc/apache2/sites-available/scotchbox.local.conf
        sudo service apache2 restart
    SHELL

end
